name: Build Windows Executable with Pyinstaller

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: echo path
        run: echo ${{ github.workspace }}

      - name: list files
        run: ll ${{ github.workspace }}

      #- name: Package Application
      #  uses: JackMcKew/pyinstaller-action-windows@main
      #  with:
      #    path: 

      #- name: Upload artifacts
      #  uses: actions/upload-artifact@v2
      #  with: 
      #    name: LOL_report.exe
      #    path: ./dist/windows