name: Build Windows Executable with Pyinstaller

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.6.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: |
          pyinstaller -F League.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: League.exe
          path: dist

      # TODO: pack the exe and images in a zip and release it
      # pack with -F not -D