name: Build Windows Executable with Pyinstaller

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: print pwd 2
      #   run: echo $PWD

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: $PWD

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: LOL_report.exe
          path: $PWD/dist/windows